### ISSUE TITLE
ReactNative.component issue causing error

### ISSUE THREAD

**Issue by skleest** [iodine/react-native-drawer-layout#79]
Seems to be the same issue as: https://github.com/facebook/react-native/issues/8436
Removing this module fixed the error. Any ideas? Thanks!

**Comment by skleest** [comment]
Fixed by uninstalling/reinstalling module

**Comment by jmuchaxo** [comment]
What module?  I tried remove and install again react-redux react react-native and still face the same issue 
I am compiling latest https://github.com/kauffecup/react-native-web-hello-world

**Comment by skleest** [comment]
I npm uninstalled this model and reinstalled, started working. RN 0.39.2
